### ISSUE TITLE
[Improvement] Cross-Domain event emitter

### ISSUE THREAD

**Issue by julianxhokaxhiu** [fabioricali/flak#1]
Hi,

I saw that your project resembles more or less the idea I had in my own project called PostEvent ( https://github.com/julianxhokaxhiu/PostEvent ).

If you would add the cross-domain support through postMessage I guess your library would definitely super seed mine.

Best regards,
Julian

**Comment by fabiorc428** [comment]
Hi Julian,

thanks for your suggestion, it's a great improvement! I put it in todo list.
